import NN_predict
# print(NN_predict.model_predict("латун", "LSTM", True))
# print(NN_predict.model_predict("бронза","LSTM", True))
# print(NN_predict.model_predict("серебро","LSTM", True))
# print(NN_predict.model_predict("золото","LSTM", True))
# print(NN_predict.model_predict("пупупу","LSTM", True))
# print(NN_predict.model_predict("военный","LSTM", True))
# print(NN_predict.model_predict("гробничий","LSTM", True))
#
# print(NN_predict.model_predict("ст. 12Х18Н9Т","LSTM", True))
# print(NN_predict.model_predict("TP316L","LSTM", True))
# print(NN_predict.model_predict("005-007-14-2","LSTM", True))
# print(NN_predict.model_predict("ic-7,6-2,4-1175","LSTM", True))
# print(NN_predict.model_predict("ii-2-150/100х200 амг-ом1","LSTM", True))
# print(NN_predict.model_predict("секф.467256.001-02","LSTM", True))

print(NN_predict.model_predict("латун", "", False))
print(NN_predict.model_predict("бронза","", False))
print(NN_predict.model_predict("серебро","", False))
print(NN_predict.model_predict("золото","", False))
print(NN_predict.model_predict("пупупу","", False))
print(NN_predict.model_predict("военный","", False))
print(NN_predict.model_predict("гробничий","", False))

print(NN_predict.model_predict("ст. 12Х18Н9Т","", False))
print(NN_predict.model_predict("TP316L","", False))
print(NN_predict.model_predict("005-007-14-2","", False))
print(NN_predict.model_predict("ic-7,6-2,4-1175","", False))
print(NN_predict.model_predict("ii-2-150/100х200 амг-ом1","", False))
print(NN_predict.model_predict("секф.467256.001-02","", False))