import NN_predict
# print(NN_predict.model_predict("латун", "LSTM", True))
# print(NN_predict.model_predict("бронза","LSTM", True))
# print(NN_predict.model_predict("серебро","LSTM", True))
# print(NN_predict.model_predict("золото","LSTM", True))
# print(NN_predict.model_predict("пупупу","LSTM", True))
# print(NN_predict.model_predict("военный","LSTM", True))
# print(NN_predict.model_predict("гробничий","LSTM", True))
#
# print(NN_predict.model_predict("ст. 12Х18Н9Т","LSTM", True))
# print(NN_predict.model_predict("TP316L","LSTM", True))
# print(NN_predict.model_predict("005-007-14-2","LSTM", True))
# print(NN_predict.model_predict("ic-7,6-2,4-1175","LSTM", True))
# print(NN_predict.model_predict("ii-2-150/100х200 амг-ом1","LSTM", True))
# print(NN_predict.model_predict("секф.467256.001-02","LSTM", True))
aa = dict()

# aa["латун"] = NN_predict.model_predict("латун", "resnet34", False)
# aa["бронза"] =NN_predict.model_predict("бронза","resnet34", False)
# aa["серебро"] =NN_predict.model_predict("серебро","resnet34", False)
# aa["resnet34"] =NN_predict.model_predict("resnet34","resnet34", False)
# aa["золото"] =NN_predict.model_predict("золото","resnet34", False)
# aa["пупупу"] =NN_predict.model_predict("пупупу","resnet34", False)
# aa["военный"] =NN_predict.model_predict("военный","resnet34", False)
# aa["гробничий"] =NN_predict.model_predict("гробничий","resnet34", False)
# aa["ст. 12Х18Н9Т"] =NN_predict.model_predict("ст. 12Х18Н9Т","resnet34", False)
# aa["TP316L"] =NN_predict.model_predict("TP316L","resnet34", False)
# aa["005-007-14-2"] =NN_predict.model_predict("005-007-14-2","resnet34", False)
# aa["ic-7,6-2,4-1175"] =NN_predict.model_predict("ic-7,6-2,4-1175","resnet34", False)
# aa["ii-2-150/100х200 амг-ом1"] =NN_predict.model_predict("ii-2-150/100х200 амг-ом1","resnet34", False)
# aa["секф.467256.001-02"] =NN_predict.model_predict("секф.467256.001-02","resnet34", False)

list_of_words = ["латун", "бронза","серебро","resnet34","золото","пупупу","военный","шрирача", "лапша", "ст. 12Х18Н9Т","TP316L","005-007-14-2","ic-7,6-2,4-1175","ii-2-150/100х200 амг-ом1","секф.467256.001-02"]

print(NN_predict.mass_model_predict(list_of_words, "resnet34_bin", False))
# print(aa)
print(NN_predict.mass_model_predict(list_of_words, "resnet34_weight", False, 2))
print(NN_predict.mass_model_predict(list_of_words, "resnet34_smote", False))