import NN_predict
# print(NN_predict.model_predict("латун", "LSTM", True))
# print(NN_predict.model_predict("бронза","LSTM", True))
# print(NN_predict.model_predict("серебро","LSTM", True))
# print(NN_predict.model_predict("золото","LSTM", True))
# print(NN_predict.model_predict("пупупу","LSTM", True))
# print(NN_predict.model_predict("военный","LSTM", True))
# print(NN_predict.model_predict("гробничий","LSTM", True))
#
# print(NN_predict.model_predict("ст. 12Х18Н9Т","LSTM", True))
# print(NN_predict.model_predict("TP316L","LSTM", True))
# print(NN_predict.model_predict("005-007-14-2","LSTM", True))
# print(NN_predict.model_predict("ic-7,6-2,4-1175","LSTM", True))
# print(NN_predict.model_predict("ii-2-150/100х200 амг-ом1","LSTM", True))
# print(NN_predict.model_predict("секф.467256.001-02","LSTM", True))

print(NN_predict.model_predict("латун", "-resnet34", False))
print(NN_predict.model_predict("бронза","-resnet34", False))
print(NN_predict.model_predict("серебро","-resnet34", False))
print(NN_predict.model_predict("золото","-resnet34", False))
print(NN_predict.model_predict("пупупу","-resnet34", False))
print(NN_predict.model_predict("военный","-resnet34", False))
print(NN_predict.model_predict("гробничий","-resnet34", False))

print(NN_predict.model_predict("ст. 12Х18Н9Т","-resnet34", False))
print(NN_predict.model_predict("TP316L","-resnet34", False))
print(NN_predict.model_predict("005-007-14-2","-resnet34", False))
print(NN_predict.model_predict("ic-7,6-2,4-1175","-resnet34", False))
print(NN_predict.model_predict("ii-2-150/100х200 амг-ом1","-resnet34", False))
print(NN_predict.model_predict("секф.467256.001-02","-resnet34", False))